[Interface]
Address = 10.10.10.1/24
SaveConfig = true
# Reglas críticas de iptables para permitir el enrutamiento hacia Docker
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o ens3 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o ens3 -j MASQUERADE
ListenPort = 51820
PrivateKey = <CLAVE_PRIVADA_HUB_OCULTA>

[Peer]
# Nodo 2 (Compañero 1)
PublicKey = <CLAVE_PUBLICA_NODO2>
AllowedIPs = 10.10.10.2/32
Endpoint = <IP_PUBLICA_OPCIONAL>:29320

[Peer]
# Nodo 3 (Compañero 2)
PublicKey = <CLAVE_PUBLICA_NODO3>
AllowedIPs = 10.10.10.3/32

[Peer]
# Nodo 4 (Compañero 3)
PublicKey = <CLAVE_PUBLICA_NODO4>
AllowedIPs = 10.10.10.4/32