[Interface]
PrivateKey = <CLAVE_PRIVADA_SPOKE_OCULTA>
# La IP cambiará dependiendo del nodo (10.10.10.2, .3 o .4)
Address = 10.10.10.X/24

[Peer]
PublicKey = <CLAVE_PUBLICA_DEL_HUB>
# IP pública o dominio donde está expuesta la VM Arch Linux del Hub
Endpoint = <IP_PUBLICA_DEL_HUB>:51820
AllowedIPs = 10.10.10.0/24
PersistentKeepalive = 25