version: '3.8'

services:
  worker:
    image: nginx:alpine
    deploy:
      replicas: 4
    ports:
      - "10.10.10.2:8080-8083:80" #Aqui va la IP establecida para cada uno de ustedes
    restart: unless-stopped
